import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "module";
import { execSync } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Build stamp shown in Settings → About so builds can be compared across
// devices (issue #373). Falls back to "unknown" when git is unavailable. In
// watch mode it is captured once, when watching starts.
function git(args) {
	try {
		return execSync(`git ${args}`, { stdio: ["ignore", "pipe", "ignore"] })
			.toString()
			.trim();
	} catch {
		return "";
	}
}
const buildInfo = {
	commit: git("rev-parse --short HEAD") || "unknown",
	dirty: git("status --porcelain") !== "",
	builtAt: new Date().toISOString(),
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"moment",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		__RSS_DASHBOARD_BUILD__: JSON.stringify(buildInfo),
	},
	loader: {
		".json": "json",
		".wasm": "binary",
		// Curated What's New notes are bundled as plain text; only the text is
		// embedded, images stay remote.
		".md": "text"
	}
});

// CSS bundling: resolves @import in src/styles/index.css → styles.css
const cssContext = await esbuild.context({
	entryPoints: ["src/styles/index.css"],
	bundle: true,
	outfile: "styles.css",
	logLevel: "info",
	minify: prod,
});

if (prod) {
	try {
		await Promise.all([context.rebuild(), cssContext.rebuild()]);
		console.log("Build complete: main.js and styles.css have been updated.");
		process.exit(0);
	} catch (err) {
		console.error("Build failed:", err);
		process.exit(1);
	}
} else {
	await Promise.all([context.watch(), cssContext.watch()]);
	console.log("Watch mode active: main.js and styles.css are being watched.");
}
