export const FEED_REQUEST_TIMEOUT_MS = 30000;
export const BACKGROUND_IMPORT_FEED_REQUEST_TIMEOUT_MS = 30000;
export const FEED_SOFT_TIMEOUT_MS = 5000;
export const MAX_CONCURRENT_FETCHES = 8;
export const BACKGROUND_IMPORT_TIMEOUT_RETRY_COUNT = 0;
export const BACKGROUND_IMPORT_CONCURRENCY = 2;
