export const FEED_REQUEST_TIMEOUT_MS = 15000;
export const BACKGROUND_IMPORT_FEED_REQUEST_TIMEOUT_MS = 30000;
export const BACKGROUND_IMPORT_TIMEOUT_RETRY_COUNT = 1;
export const BACKGROUND_IMPORT_CONCURRENCY = 2;
