name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Create release assets
        run: |
          # Create a release directory
          mkdir -p release
          
          # Copy main files
          cp main.js manifest.json styles.css release/
          
          # Create zip file for easy distribution
          cd release
          zip -r ../obsidian-rss-dashboard.zip .
          cd ..

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          
          # Create release with all assets
          gh release create "$tag" \
            --title="$tag" \
            --notes="Release $tag" \
            --draft \
            main.js \
            manifest.json \
            styles.css \
            obsidian-rss-dashboard.zip